class SharedPrefKeys {
  static const String userToken =
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3ZjYXJlLmludGVncmF0aW9uMjUuY29tL2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNzgwNzAxMjAxLCJleHAiOjE3ODA3ODc2MDEsIm5iZiI6MTc4MDcwMTIwMSwianRpIjoiWWc1ajdxOTJBcmJPempVdCIsInN1YiI6IjcwOTQiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.AbCXzvdNFeRF85jl9uWd0oUTVt-hfzMYmbuuVfjaYr4';
}
